Repository helidon-io/helidon-mcp, pull requests merged in 2025-09, with the labels that each got.

#34 Support for MCP features and SSE
  examples/calendar/pom.xml
  examples/weather-application/mcp-client/pom.xml
  examples/weather-application/mcp-server-declarative/pom.xml
  examples/weather-application/mcp-server/pom.xml
  pom.xml
  server/src/main/java/io/helidon/extensions/mcp/server/McpFeature.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpFeatures.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpLogger.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpProgress.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpServerFeature.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpSession.java
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/LoggingNotifications.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/AbstractMcpSdkLoggingTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/McpSdkSseLoggingTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/McpSdkStreamableLoggingDebugTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/McpSdkStreamableLoggingTest.java
Labels: enhancement, OCA Verified

#38 Add resolved parameters for Resource templates
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpCodegen.java
  docs/mcp-declarative/README.md
  docs/mcp/README.md
  examples/calendar/pom.xml
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/Calendar.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/CalendarEventResourceTemplate.java
  examples/calendar/src/test/java/io/helidon/extensions/mcp/examples/calendar/BaseTest.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpJsonRpc.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpResourceTemplate.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpServerFeature.java
  server/src/test/java/io/helidon/extensions/mcp/server/McpResourceTemplateParameterTest.java
  server/src/test/java/io/helidon/extensions/mcp/server/McpResourceTemplatePathMatchingTest.java
  tests/declarative/src/main/java/io/helidon/extensions/mcp/tests/declarative/McpResourceTemplatesServer.java
  tests/declarative/src/test/java/io/helidon/extensions/mcp/tests/declarative/AbstractLangchain4jResourceTemplatesServerTest.java
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/MultipleResourceTemplate.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/AbstractLangchain4jMultipleResourceTemplateTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/Langchain4jStreamableMultipleResourceTemplateTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/McpSdkMultipleResourceTemplateTest.java
Labels: OCA Verified

#51 Updates docs with new audio type and some other minor fixes
  docs/mcp/README.md
Labels: documentation, enhancement, OCA Verified

#52 Improve support for prompt and resource completions
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpCodegen.java
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpTypes.java
  docs/mcp-declarative/README.md
  docs/mcp/README.md
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/Calendar.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/CalendarEventResource.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/CalendarEventResourceCompletion.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/CreateCalendarEventPrompt.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/CreateCalendarEventPromptCompletion.java
  examples/calendar/src/main/java/io/helidon/extensions/mcp/examples/calendar/Main.java
  examples/calendar/src/test/java/io/helidon/extensions/mcp/examples/calendar/BaseTest.java
  server/src/main/java/io/helidon/extensions/mcp/server/Mcp.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpCompletionBlueprint.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpCompletionType.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpJsonRpc.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpServerFeature.java
  server/src/test/java/io/helidon/extensions/mcp/server/McpCompletionTest.java
  tests/codegen/src/test/java/io/helidon/extensions/mcp/codegen/McpTypesTest.java
  tests/declarative/src/main/java/io/helidon/extensions/mcp/tests/declarative/McpCompletionsServer.java
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/CompletionNotifications.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/AbstractMcpSdkCompletionTest.java
Labels: enhancement, OCA Verified

#46 Add Cancellation feature
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpCodegen.java
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpTypes.java
  docs/mcp-declarative/README.md
  docs/mcp/README.md
  server/src/main/java/io/helidon/extensions/mcp/server/McpCancellation.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpCancellationResult.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpFeatures.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpServerFeature.java
  server/src/main/java/io/helidon/extensions/mcp/server/McpSession.java
  server/src/test/java/io/helidon/extensions/mcp/server/McpCancellationTest.java
  tests/codegen/src/test/java/io/helidon/extensions/mcp/codegen/McpTypesTest.java
  tests/declarative/src/main/java/io/helidon/extensions/mcp/tests/declarative/McpCancellationServer.java
  tests/declarative/src/test/java/io/helidon/extensions/mcp/tests/declarative/AbstractLangchain4jCancellationServerTest.java
  tests/declarative/src/test/java/io/helidon/extensions/mcp/tests/declarative/Langchain4jSseCancellationServerTest.java
  tests/declarative/src/test/java/io/helidon/extensions/mcp/tests/declarative/Langchain4jStreamableCancellationServerTest.java
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/CancelableTools.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/AbstractLangchain4JCancelableToolsTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/Langchain4JSseCancelableToolsTest.java
  tests/mcp/src/test/java/io/helidon/extensions/mcp/tests/Langchain4JStreamableCancelableToolsTest.java
Labels: enhancement, OCA Verified

#61 Initial support for Helidon JSON schema
  codegen/pom.xml
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpJsonSchemaCodegen.java
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpJsonSchemaCodegenProvider.java
  codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpTypes.java
  codegen/src/main/java/module-info.java
  docs/mcp-declarative/README.md
  docs/mcp/README.md
  examples/weather-application/mcp-server/pom.xml
  examples/weather-application/mcp-server/src/main/java/io/helidon/extensions/mcp/weather/server/Main.java
  server/src/main/java/io/helidon/extensions/mcp/server/Mcp.java
  tests/codegen/src/test/java/io/helidon/extensions/mcp/codegen/McpTypesTest.java
  tests/declarative/pom.xml
  tests/declarative/src/main/java/io/helidon/extensions/mcp/tests/declarative/McpMixedComponentServer.java
  tests/declarative/src/main/java/io/helidon/extensions/mcp/tests/declarative/McpToolsServer.java
  tests/declarative/src/main/java/module-info.java
  tests/declarative/src/test/java/io/helidon/extensions/mcp/tests/declarative/JsonSchemaGenerationTest.java
  tests/mcp/pom.xml
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/MultipleTool.java
  tests/mcp/src/main/java/io/helidon/extensions/mcp/tests/PaginationServer.java
  tests/mcp/src/main/java/module-info.java
Labels: enhancement, OCA Verified, incompatible change
